name: 'action-fpm'
description: 'Build packages for multiple platforms using github.com/jordansissel/fpm'
branding:
  icon: 'package'  
  color: 'green'
inputs:
  fpm_opts:
    description: 'Options passed to the fpm cli tool'
    required: true
  fpm_args:
    description: 'Arguments passed to the fpm cli tool'
    required: true
runs:
  using: 'docker'
  image: 'docker://docker.io/gravitl/github-action-fpm'
  args:
    - ${{ inputs.fpm_args }}
